plugins:
  eslint:
    enabled: false
    channel: "eslint-7"
    config:
      file: .eslintrc.json
  rubocop:
    enabled: true
    channel: "rubocop-1-9-1"
    config:
      file: .rubocop.yml
  exlude_patterns:
    - 'public/**/*'
    - 'node_modules/**/*'
