image: docker:latest

before_script:
  - docker info

include:
  - template: Code-Quality.gitlab-ci.yml
  - '.gitlab-ci/*.yml'

stages:
  - build_test_image
  - test
  - build_image
  - push_image
  - deploy_production
  - migrate_db
