stages:
  - build_image
  - push_image
  - deploy_production
  - migrate_db

before_script:
  - docker info

build_test_image:
  only:
    - master
  stage: build_image
  script:
    - docker build -f Dockerfile.test -t gpiu-national-dev:latest .

test_image:
  only:
    - master
  stage: build_image
  script:
    - docker run --rm gpiu-national-dev:latest bundle exec rspec

build_image:
  only:
    - master
  stage: build_image
  script:
    - docker build -t gpiu-registry.mni.thm.de/gpiu-national:latest .

push_image:
  only:
    - master
  stage: push_image
  script:
    - docker push gpiu-registry.mni.thm.de/gpiu-national:latest

deploy_production:
  only:
    - master
  stage: deploy_production
  script:
    - docker stack rm gpiu-national
    - sleep 10
    - docker stack deploy -c gpiu-national-stack-prod.yml gpiu-national --with-registry-auth
  environment:
    name: production
    url: https://national.esiu.org/
    on_stop: stop_production

stop_production:
  only:
    - master
  stage: deploy_production
  variables:
    GIT_STRATEGY: none
  when: manual
  script:
    - docker stack rm gpiu-national
  environment:
    name: production
    action: stop

migrate_db:
  only:
    - master
  stage: migrate_db
  variables:
    GPIU_NAT_DB_HOST: db
    GPIU_NAT_DB_NAME: GpiuNational
    GPIU_NAT_DB_USER: prod
    GPIU_NAT_DB_PASSWORD: gpiu-national
    RAILS_ENV: production
  script: docker run --network=gpiu-national_gpiu_national_prod_net  -e GPIU_NAT_DB_HOST  -e GPIU_NAT_DB_NAME -e GPIU_NAT_DB_USER -e GPIU_NAT_DB_PASSWORD -e RAILS_ENV -t gpiu-registry.mni.thm.de/gpiu-national:latest  rails db:migrate

# Staging System

build_test_image_staging:
  only:
    - staging
  stage: build_image
  script:
    - docker build -f Dockerfile.test -t gpiu-national-dev:staging .

test_image_staging:
  only:
    - staging
  stage: build_image
  script:
    - docker run --rm gpiu-national-dev:staging bundle exec rspec

build_image_staging:
  only:
    - staging
  stage: build_image
  script:
    - docker build -t gpiu-registry.mni.thm.de/gpiu-national:staging .

push_image_staging:
  only:
    - staging
  stage: push_image
  script:
    - docker push gpiu-registry.mni.thm.de/gpiu-national:staging

deploy_staging:
  only:
    - staging
  stage: deploy_production
  script:
    - docker stack rm gpiu-national-staging
    - sleep 10
    - docker stack deploy -c gpiu-national-stack-staging.yml gpiu-national-staging --with-registry-auth
  environment:
    name: staging
    url: https://national.staging.esiu.org/
    on_stop: stop_staging

stop_staging:
  only:
    - staging
  stage: deploy_production
  variables:
    GIT_STRATEGY: none
  when: manual
  script:
    - docker stack rm gpiu-national-staging
  environment:
    name: staging
    action: stop

migrate_db_staging:
  only:
    - staging
  stage: migrate_db
  variables:
    GPIU_NAT_DB_HOST: db
    GPIU_NAT_DB_NAME: GpiuNational
    GPIU_NAT_DB_USER: staging
    GPIU_NAT_DB_PASSWORD: gpiu-national
    RAILS_ENV: production
  script: docker run --network=gpiu-national-staging_gpiu_national_staging_net -e GPIU_NAT_DB_HOST  -e GPIU_NAT_DB_NAME -e GPIU_NAT_DB_USER -e GPIU_NAT_DB_PASSWORD -e RAILS_ENV -t gpiu-registry.mni.thm.de/gpiu-national:staging  rails db:migrate

# Development/Test

build_image_dev:
  only:
    - dev
  stage: build_image
  script:
    - docker build -f Dockerfile.test -t gpiu-national-dev .

test_image_dev:
  only:
    - dev
  stage: build_image
  script:
    - docker run --rm gpiu-national-dev bundle exec rspec
