FROM ruby:2.7.5-alpine3.15 as BUILDER

RUN apk update && apk -U upgrade \
    && apk add build-base \
    tini \
    openssh \
    nodejs \
    git \
    postgresql-dev \
    sqlite-dev \
    tzdata \
    yarn \
    python3 python3-dev py3-pip

WORKDIR /app

# Install gems, clean unneeded files
COPY Gemfile* /app/
RUN bundle config set with 'development test' \
    && bundle install -j4 --retry 3 \
    && rm -rf /usr/local/bundle/cache/*.gem \
    && find /usr/local/bundle/gems/ -name "*.c" -delete \
    && find /usr/local/bundle/gems/ -name "*.o" -delete

# Install JS dependencies
COPY package.json yarn.lock /app/
RUN yarn install

# Copy the app source
COPY . /app

# Precompile assets
RUN RAILS_ENV=test bundle exec rake assets:precompile

# Remove folders not needed in resulting image
RUN rm -rf node_modules tmp/cache

FROM ruby:2.7.5-alpine3.15

RUN apk update && apk -U upgrade \
    && apk add tini \
    sqlite \
    chromium chromium-chromedriver \
    tzdata

COPY --from=BUILDER /usr/local/bundle/ /usr/local/bundle/
COPY --from=BUILDER /app /app

WORKDIR /app

EXPOSE 3000
