version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - gpiu_national_staging_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: staging
      POSTGRES_DB: GpiuNational
      POSTGRES_PASSWORD: gpiu-national
    networks:
      - gpiu_national_staging_net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.hostname == gpiu-db]

  web:
    image: gpiu-registry.mni.thm.de/gpiu-national:staging
    depends_on:
      - db
    environment:
      - GPIU_NAT_DB_HOST=db
      - GPIU_NAT_DB_NAME=GpiuNational
      - GPIU_NAT_DB_USER=staging
      - GPIU_NAT_DB_PASSWORD=gpiu-national
      - GPIU_NAT_REDIS_URL=redis:6379
      - GPIU_STAGING=1
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - KEYCLOAK_REALM=ESIU
      - KEYCLOAK_URL=https://sso.esiu.org
      - KEYCLOAK_INTERNAL_URL=http://10.0.8.20:8080
      - KEYCLOAK_CLIENT=national-staging
      - KEYCLOAK_CLIENT_SECRET=5c416155-9e00-455c-bcd2-76e6b3f41cc6
    networks:
      - gpiu_national_staging_net
      - traefik-net
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - "node.hostname!=gpiu-db"
      labels:
        - "traefik.enable=true"

        - "traefik.http.routers.gpiu-national-staging.entrypoints=websecure"
        - "traefik.http.routers.gpiu-national-staging.rule=Host(`national.staging.esiu.org`)"
        - "traefik.http.services.gpiu-national-staging-service.loadbalancer.server.port=3000"
        - "traefik.http.routers.gpiu-national-staging.tls=true"

  redis:
    image: 'redis:4.0-alpine'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.hostname == gpiu-db]
    networks:
      - gpiu_national_staging_net
    volumes:
      - 'redis_db:/data'

  sidekiq:
    image: gpiu-registry.mni.thm.de/gpiu-national:staging
    depends_on:
      - db
      - redis
    command: sidekiq -C config/sidekiq.yml
    environment:
      - GPIU_NAT_DB_HOST=db
      - GPIU_NAT_DB_NAME=GpiuNational
      - GPIU_NAT_DB_USER=staging
      - GPIU_NAT_DB_PASSWORD=gpiu-national
      - GPIU_NAT_REDIS_URL=redis:6379
      - GPIU_STAGING=1
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - "node.hostname!=gpiu-db"
    networks:
      - gpiu_national_staging_net

volumes:
  redis_db:
  gpiu_national_staging_db:

networks:
  gpiu_national_staging_net:
    driver: overlay
    attachable: true
  traefik-net:
    external: true
