version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - gpiu_national_staging_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: staging
      POSTGRES_DB: GpiuNational
      POSTGRES_PASSWORD: gpiu-national
    networks:
      - gpiu_national_staging_net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.hostname == gpiu-db]

  web:
    image: gpiu-registry.mni.thm.de/gpiu-national:staging
    depends_on:
      - db
    environment:
      - GPIU_NAT_DB_HOST=db
      - GPIU_NAT_DB_NAME=GpiuNational
      - GPIU_NAT_DB_USER=staging
      - GPIU_NAT_DB_PASSWORD=gpiu-national
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
    networks:
      - gpiu_national_staging_net
      - traefik-net
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - "node.hostname!=gpiu-db"
      labels:
        - "traefik.enable=true"

        - "traefik.http.routers.gpiu-national-staging.entrypoints=websecure"
        - "traefik.http.routers.gpiu-national-staging.rule=Host(`national.staging.esiu.org`)"
        - "traefik.http.services.gpiu-national-staging-service.loadbalancer.server.port=3000"
        - "traefik.http.routers.gpiu-national-staging.tls=true"

volumes:
  gpiu_national_staging_db:

networks:
  gpiu_national_staging_net:
    driver: overlay
  traefik-net:
    external: true
