build_test_image:
  stage: build_test_image
  script:
    - docker build -f Dockerfile.test -t gpiu-national-test:$CI_COMMIT_SHORT_SHA .
  tags:
    - esiu
    - build

# <============================================================================>

include:
  - template: Code-Quality.gitlab-ci.yml

rspec:
  stage: test
  script:
    - mkdir -p $PWD/coverage
    - docker run --rm -v $PWD/coverage:/app/coverage -e SIMPLECOV_COBERTURA gpiu-national-test:$CI_COMMIT_SHORT_SHA bundle exec rspec --format documentation
  variables:
    SIMPLECOV_COBERTURA: "true"
  artifacts:
    reports:
      cobertura: coverage/coverage.xml
  tags:
    - esiu
    - build
